---
nagios_server_ip: "{{ hostvars['ng_server1']['ansible_host'] }}"
wordpress_server_ip: "{{ hostvars['wp_server1']['ansible_host'] }}"
docker_server_ip: "{{ hostvars['dk_server1']['ansible_host'] }}"

wordpress_table_prefix: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/wordpress.wordpress_table_prefix', nested=true) }}"
wordpress_debug: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/wordpress.wordpress_debug', nested=true) }}"

mysql_root_password: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/mysql.mysql_root_password', nested=true) }}"
mysql_bind_address: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/mysql.mysql_bind_address', nested=true) }}"
wordpress_db_user: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/mysql.wordpress_db_user', nested=true) }}"
wordpress_db_password: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/mysql.wordpress_db_password', nested=true) }}"
wordpress_db_name: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/mysql.wordpress_db_name', nested=true) }}"
wordpress_db_host: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/mysql.wordpress_db_host', nested=true) }}"

nagios_version: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/nagios.nagios_version', nested=true) }}"
nagios_plugins_version: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/nagios.nagios_plugins_version', nested=true) }}"
nagios_user: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/nagios.nagios_user', nested=true) }}"
nagios_group: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/nagios.nagios_group', nested=true) }}"
nagios_admin_user: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/nagios.nagios_admin_user', nested=true) }}"
nagios_admin_password: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/nagios.nagios_admin_password', nested=true) }}"

nrpe_version: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/nagios.nrpe_version', nested=true) }}"
plugin_version: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/nagios.plugin_version', nested=true) }}"
nrpe_user: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/nagios.nrpe_user', nested=true) }}"
nrpe_group: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/nagios.nrpe_group', nested=true) }}"

prometheus_version: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/prometheus.prometheus_version', nested=true) }}"
prometheus_user: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/prometheus.prometheus_user', nested=true) }}"
prometheus_group: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/prometheus.prometheus_group', nested=true) }}"

apache_exporter_user: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/prometheus.apache_exporter_user', nested=true) }}"
apache_exporter_group: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/prometheus.apache_exporter_group', nested=true) }}"
apache_exporter_version: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/prometheus.apache_exporter_version', nested=true) }}"

node_exporter_version: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/prometheus.node_exporter_version', nested=true) }}"
node_exporter_user: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/prometheus.node_exporter_user', nested=true) }}"
node_exporter_group: "{{ lookup('amazon.aws.aws_secret', 'dev/ansible/prometheus.node_exporter_group', nested=true) }}"