---
- name: Copy Alert Manager service configuration
  template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
  notify: 
    - Enable Alert Manager service
    - Restart Alert Manager service
