---
- name: Enable NRPE Service
  service:
    name: nrpe
    enabled: yes
    state: started
  notify: Restart NRPE Service

- name: Restart NRPE Service
  service:
    name: nrpe
    state: restarted