Vagrant.configure("2") do |config|
  config.vm.define "nagios-server" do |node|
    node.vm.box = "centos/7"

    node.vm.network "private_network", ip: "192.168.55.2"

    node.vm.hostname = "nagios-server"

    node.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end

    # node.vm.provision "shell", path: "script.sh"
  end
end