---
- name: Install Apace Exporter
  unarchive:
    src: https://github.com/Lusitaniae/apache_exporter/releases/download/v{{ apache_exporter_version }}/apache_exporter-{{ apache_exporter_version }}.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes
