---
- name: Install apache_exporter
  include_tasks: install.yml

- name: Create user for apache_exporter
  include_tasks: user.yml

- name: Configure apache_exporter
  include_tasks: binary.yml

- name: Create apache_exporter service
  include_tasks: service.yml

- name: Configure Apache for apache_exporter
  include_tasks: httpd.yml
