---
- name: Create apache_exporter service file
  template:
    src: apache_exporter.service.j2
    dest: /etc/systemd/system/apache_exporter.service
  become: true
  notify: Start and Enable apache_exporter