---
- name: Ensure SELinux allows web server to write to WordPress
  seboolean:
    name: httpd_can_network_connect_db
    state: yes

- name: Set up Apache VirtualHost
  template:
    src: "wordpress.conf.j2"
    dest: "/etc/httpd/conf.d/wordpress.conf"
  notify: Restart Apache

- name: Wordpress | Copy wp-config.php file content
  template:  
    src: wp-config.php.j2
    dest: "/var/www/html/wp-config.php"
  notify: 
    - Start and Enable Apache
    - Restart Apache
