---
- name: Enable Prometheus service
  systemd:
    name: prometheus
    enabled: yes
    daemon_reload: yes
    state: started

- name: Restart Prometheus service
  systemd:
    name: prometheus
    state: restarted