---
- name: Update the system
  yum:
    name: '*'
    state: latest

- name: Download Grafana binary
  get_url:
    url: "https://dl.grafana.com/oss/release/grafana-{{ grafana_version }}.linux-amd64.tar.gz"
    dest: "/tmp/grafana-{{ grafana_version }}.tar.gz"
    validate_certs: yes
    
- name: Extract Grafana binary
  unarchive:
    src: "/tmp/grafana-{{ grafana_version }}.tar.gz"
    dest: "/etc/grafana"
    remote_src: yes
    extra_opts: [--strip-components=1]
