---
- name: Install MySQL packages and dependencies
  import_tasks: install.yml

- name: Configure MySQL
  import_tasks: mysql_secure_installation.yml

- name: Create MySQL database and User
  import_tasks: database.yml
