---
- name: Build and Install Nagios NRPE Agent
  shell: |
    ./configure --enable-command-args 
    make all
    make install-groups-users
    make install
    make install-config
    make install-init
  args:
    chdir: /tmp/nrpe-nrpe-{{ nrpe_version }}

- name: Build and Install Nagios NRPE Plugins
  shell: |
    ./configure
    make
    make install
  args:
    chdir: /tmp/nagios-plugins-{{ plugin_version }}


