---
- name: Add IP to allowed_hosts in nrpe.cfg
  lineinfile:
    path: /usr/local/nagios/etc/nrpe.cfg
    regexp: '^allowed_hosts='
    line: 'allowed_hosts=127.0.0.1,{{ nagios_server_ip }}'

- name: Set dont_blame_nrpe to 1 in nrpe.cfg
  lineinfile:
    path: /usr/local/nagios/etc/nrpe.cfg
    regexp: '^dont_blame_nrpe='
    line: 'dont_blame_nrpe=1'

- name: Update services file with NRPE Service Name, Port and Protocol
  lineinfile:
    path: /etc/services
    line: "nrpe            5666/tcp                # NRPE Service"

- name: Add scripts
  template:
    src: "{{ item }}"
    dest: /usr/local/nagios/libexec/{{ item | basename | regex_replace('\\.j2$', '') }}
    owner: nagios
    group: nagios
    mode: 0755
  loop:
    - check_apache.j2
    - check_processes.j2
    - check_wordpress.j2
    - check_disk_space.j2

- name: Add check commands to NRPE config
  lineinfile:
    path: /usr/local/nagios/etc/nrpe.cfg
    line: "{{ item }}"
    insertafter: EOF
    state: present
  loop:
    - command[check_apache]=/usr/local/nagios/libexec/check_apache
    - command[check_processes]=/usr/local/nagios/libexec/check_processes
    - command[check_wordpress]=/usr/local/nagios/libexec/check_wordpress
    - command[check_disk_space]=/usr/local/nagios/libexec/check_disk_space

- name: Disable SSL when running NRPE Agent 
  replace:
    path: /usr/lib/systemd/system/nrpe.service
    regexp: '-f$'
    replace: '-f -n'

- name: Start and Enable NRPE to run on System boot
  systemd:
    name: nrpe
    daemon_reload: yes
    state: restarted
    enabled: true