---
nagios_version: 4.5.0
nagios_plugins_version: 2.4.6
nrpe_version: 4.1.0
plugin_version: 2.4.7
nagios_server_ip: "{{ hostvars['ng_server1']['ansible_host'] }}"
wordpress_server_ip: "{{ hostvars['wp_server1']['ansible_host'] }}"
docker_server_ip: "{{ hostvars['dk_server1']['ansible_host'] }}"
