---
- name: Create htpasswd file
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: nagiosadmin
    password: "{{ nagios_admin_password }}"
    state: present
  notify: 
    - restart apache
    - restart nagios