---
- name: Create htpasswd file
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: "{{ nagios_admin_user }}"
    password: "{{ nagios_admin_password }}"
    state: present
  notify: 
    - Restart Apache
    - Restart Nagios