---
- name: Create Nagios user and group
  user:
    name: nagios
    group: nagios
    createhome: yes
    system: yes

- name: Change ownership of Nagios directories
  file:
    path: "{{ item }}"
    owner: nagios
    group: nagios
    mode: 0755
    recurse: yes
  loop:
    - /usr/local/nagios
    - /usr/local/nagios/libexec
    - /usr/local/nagios/var
    - /tmp/nagios-{{ nagios_version }}

- name: Compile Nagios Core
  command: "./configure"
  args:
    chdir: "/tmp/nagios-{{ nagios_version }}"

- name: Install Nagios Core
  command: "make all"
  args:
    chdir: "/tmp/nagios-{{ nagios_version }}"

- name: Install Nagios Core files
  command: "make install"
  args:
    chdir: "/tmp/nagios-{{ nagios_version }}"

- name: Install Nagios plugins
  command: "make install-plugin"
  args:
    chdir: "/tmp/nagios-{{ nagios_version }}/plugins"

