---
- name: Compile Nagios Core
  command: "./configure --with-httpd-conf=/etc/httpd/conf.d"
  args:
    chdir: "/tmp/nagios-{{ nagios_version }}"

- name: Install Nagios Core
  command: "make all"
  args:
    chdir: "/tmp/nagios-{{ nagios_version }}"

- name: Install Nagios Core users files
  command: "make install-groups-users"
  args:
    chdir: "/tmp/nagios-{{ nagios_version }}"

- name: Add user apache to group nagios
  user:
    name: apache
    groups: nagios
    append: yes

- name: Install Nagios Core files
  command: "make install"
  args:
    chdir: "/tmp/nagios-{{ nagios_version }}"

- name: Install Nagios daemon init
  command: make install-daemoninit
  args:
    chdir: "/tmp/nagios-{{ nagios_version }}"
  notify: restart apache

- name: Enable httpd service
  systemd:
    name: httpd.service
    enabled: yes

- name: Install Nagios Command Mode
  command: "make install-commandmode"
  args:
    chdir: "/tmp/nagios-{{ nagios_version }}"

- name: Install Nagios Configuration Files
  command: "make install-config"
  args:
    chdir: "/tmp/nagios-{{ nagios_version }}"  

- name: Install Apache Config Files
  command: "make install-webconf"
  args:
    chdir: "/tmp/nagios-{{ nagios_version }}"
  notify: restart apache

- name: restart apache
  service:
    name: httpd
    state: restarted

- name: restart nagios
  service:
    name: nagios
    state: restarted
