---
- name: Compile Nagios Core
  command: "./configure --with-httpd-conf=/etc/httpd/conf.d"
  args:
    chdir: "/tmp/nagios-{{ nagios_version }}"

- name: Install Nagios Core
  command: "make all"
  args:
    chdir: "/tmp/nagios-{{ nagios_version }}"

- name: Install Nagios Core users files
  command: "make install-groups-users"
  args:
    chdir: "/tmp/nagios-{{ nagios_version }}"

- name: Add user apache to group nagios
  user:
    name: apache
    groups: nagios
    append: yes

- name: Install Nagios Core files
  command: "make install"
  args:
    chdir: "/tmp/nagios-{{ nagios_version }}"

- name: Install Nagios plugins
  command: "make install-plugin"
  args:
    chdir: "/tmp/nagios-{{ nagios_version }}/plugins"

