---
- name: Compile Nagios Core
  command: "./configure"
  args:
    with-httpd-conf: "/etc/httpd/conf.d"
    chdir: "/tmp/nagios-{{ nagios_version }}"

- name: Install Nagios Core
  command: "make all"
  args:
    chdir: "/tmp/nagios-{{ nagios_version }}"

- name: Install Nagios Core files
  command: "make install"
  args:
    chdir: "/tmp/nagios-{{ nagios_version }}"

- name: Install Nagios plugins
  command: "make install-plugin"
  args:
    chdir: "/tmp/nagios-{{ nagios_version }}/plugins"

