---
- name: Compile and Install Nagios Core
  command: "make all"
  args:
    chdir: "/tmp/nagioscore-nagios-{{ nagios_version }}"

- name: Install Nagios Core files
  command: "make install"
  args:
    chdir: "/tmp/nagioscore-nagios-{{ nagios_version }}"

- name: Install Nagios plugins
  command: "make install-plugin"
  args:
    chdir: "/tmp/nagioscore-nagios-{{ nagios_version }}/plugins"
