---
- name: Update the system
  dnf:
    name: '*'
    state: latest
    exclude: kernel*

- name: Install required packages
  dnf:
    name: "{{ item }}"
    state: present
  loop: [ "httpd", "docker", "php", "php-cli", "gcc", "glibc", "glibc-common", "gd", "gd-devel", "make", "net-snmp", "openssl", "perl", "wget", "unzip", "openssl-devel", "python-pip", "gettext", "automake", "autoconf", "net-snmp-utils" ]

- name: Install passlib
  pip:
    name: passlib
    executable: /usr/bin/pip3

- name: Download and Extract Nagios Core source
  ansible.builtin.unarchive:
    src: "https://github.com/NagiosEnterprises/nagioscore/releases/download/nagios-{{ nagios_version }}/nagios-{{ nagios_version }}.tar.gz"
    dest: "/tmp/"
    remote_src: yes

