---
- name: Update the system
  dnf:
    name: '*'
    state: latest
    exclude: kernel*

- name: Install required packages
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - httpd
    - php
    - php-cli
    - gcc
    - glibc
    - glibc-common
    - gd
    - gd-devel
    - make
    - net-snmp
    - openssl
    - perl
    - wget
    - unzip

- name: Download Nagios Core source
  get_url:
    url: "https://github.com/NagiosEnterprises/nagioscore/releases/download/nagios-{{ nagios_version }}/nagios-{{ nagios_version }}.tar.gz"
    dest: "/tmp/nagios-{{ nagios_version }}.tar.gz"

- name: Extract Nagios Core source
  ansible.builtin.unarchive:
    src: "/tmp/nagios-{{ nagios_version }}.tar.gz"
    dest: "/tmp/"

