---
- name: Add check_nrpe command to Nagios
  blockinfile:
    path: /usr/local/nagios/etc/objects/commands.cfg
    block: |
      define command{
        command_name check_nrpe
        command_line $USER1$/check_nrpe -H $HOSTADDRESS$ -c $ARG1$
      }
    insertafter: EOF

- name: Add hosts to Nagios
  template:
    src: templates/hosts.cfg.j2
    dest: /usr/local/nagios/etc/hosts.cfg
    owner: "{{ nagios_user }}"
    group: "{{ nagios_group }}"
    mode: 0644

- name: Add services to Nagios
  template:
    src: templates/services.cfg.j2
    dest: /usr/local/nagios/etc/services.cfg
    owner: "{{ nagios_user }}"
    group: "{{ nagios_group }}"
    mode: 0644

- name: Add hosts and services to Nagios config
  lineinfile:
    path: /usr/local/nagios/etc/nagios.cfg
    line: "{{ item }}"
    insertafter: EOF
    state: present
  loop:
    - "cfg_file=/usr/local/nagios/etc/hosts.cfg"
    - "cfg_file=/usr/local/nagios/etc/services.cfg"
  notify: Restart Nagios