---
- name: Install Required Build Packages/Tools
  yum:
    name:
      - gcc
      - glibc
      - glibc-common
      - openssl
      - openssl-devel
    state: present

- name: Download and Extract NRPE Source File 
  unarchive:
    src: "https://github.com/NagiosEnterprises/nrpe/archive/nrpe-{{ nrpe_version }}.tar.gz"
    dest: /tmp
    remote_src: yes

- name: Download and Extract NRPE Plugins Source File 
  unarchive:
    src: "https://github.com/nagios-plugins/nagios-plugins/releases/download/release-{{ plugin_version }}/nagios-plugins-{{ plugin_version }}.tar.gz"
    dest: /tmp
    remote_src: yes

- name: Build and Install Nagios NRPE Agent
  shell: |
    ./configure --enable-command-args 
    make install-groups-users
    make all
    make install
    make install-config
    make install-init
  args:
    chdir: /tmp/nrpe-nrpe-{{ nrpe_version }}

- name: Build and Install Nagios NRPE Plugins
  shell: |
    ./configure
    make
    make install
  args:
    chdir: /tmp/nagios-plugins-{{ plugin_version }}

- name: Update services file with NRPE Service Name, Port and Protocol
  lineinfile:
    path: /etc/services
    line: "nrpe            5666/tcp                # NRPE Service"

- name: Add IP to allowed_hosts in nrpe.cfg
  lineinfile:
    path: /usr/local/nagios/etc/nrpe.cfg
    regexp: '^allowed_hosts='
    line: 'allowed_hosts=127.0.0.1,{{ nagios_server_ip }}'

- name: Set dont_blame_nrpe to 1 in nrpe.cfg
  lineinfile:
    path: /usr/local/nagios/etc/nrpe.cfg
    regexp: '^dont_blame_nrpe='
    line: 'dont_blame_nrpe=1'

- name: Add hosts to Nagios
  template:
    src: templates/hosts.cfg.j2
    dest: /usr/local/nagios/etc/hosts.cfg
    owner: nagios
    group: nagios
    mode: 0644

- name: Add services to Nagios
  template:
    src: templates/services.cfg.j2
    dest: /usr/local/nagios/etc/services.cfg
    owner: nagios
    group: nagios
    mode: 0644

- name: Add hosts and services to Nagios config
  lineinfile:
    path: /usr/local/nagios/etc/nagios.cfg
    line: "{{ item }}"
    insertafter: EOF
    state: present
  loop:
    - "cfg_file=/usr/local/nagios/etc/hosts.cfg"
    - "cfg_file=/usr/local/nagios/etc/services.cfg"

- name: Add nrpe command to Nagios
  blockinfile:
    path: /path/to/your/file.cfg
    block: |
      define command{
        command_name check_nrpe
        command_line $USER1$/check_nrpe -H $HOSTADDRESS$ -c $ARG1$
      }
    insertafter: EOF

- name: Disable SSL when running NRPE Agent 
  replace:
    path: /usr/lib/systemd/system/nrpe.service
    regexp: '-f$'
    replace: '-f -n'

- name: Start and Enable NRPE to run on System boot
  systemd:
    name: nrpe
    daemon_reload: yes
    state: restarted
    enabled: true