---

- name: Sutup Nagios Plugins
  command: "./tools/setup"
  args:
    chdir: "/tmp/nagios-plugins-release-{{ nagios_plugins_version }}"

- name: Compile Nagios Plugins
  command: "./configure"
  args:
    chdir: "/tmp/nagios-plugins-release-{{ nagios_plugins_version }}"

- name: Init Nagios Plugins
  command: "make"
  args:
    chdir: "/tmp/nagios-plugins-release-{{ nagios_plugins_version }}"

- name: Install Nagios Plugins
  command: "make install"
  args:
    chdir: "/tmp/nagios-plugins-release-{{ nagios_plugins_version }}"
  notify:
    - Restart Apache
    - Restart Nagios
