---
- name: Build and Install Nagios NRPE Agent
  shell: |
    ./configure --enable-command-args 
    make all
    make install-groups-users
    make install
    make install-config
  args:
    chdir: /tmp/nrpe-nrpe-{{ nrpe_version }}

- name: Initialize Nagios Agent
  command: make install-init
  args:
    chdir: /tmp/nrpe-nrpe-{{ nrpe_version }}

- name: Enable NRPE Service
  service:
    name: nrpe
    enabled: yes
    state: started

- name: Build and Install Nagios NRPE Plugins
  shell: |
    ./configure
    make
    make install
  args:
    chdir: /tmp/nagios-plugins-{{ plugin_version }}

- name: Restart NRPE Service
  service:
    name: nrpe
    state: restarted
