---
- name: Add daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  become: true

- name: Restart Docker
  service:
    name: docker
    state: restarted
  become: true