---
- name: Start and Enable node_exporter
  service:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes
  become: true

- name: Restart node_exporter
  service:
    name: node_exporter
    state: restarted
    enabled: yes
