---
- name: Install Prometheus and Dependencies
  include_tasks: install.yml

- name: Configure permissions
  include_tasks: permisions.yml

- name: Configure Prometheus
  include_tasks: configure.yml

- name: Configure Prometheus service
  include_tasks: service.yml
