---
- name: Copy Prometheus service configuration
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify: 
    - Enable Prometheus service
    - Restart Prometheus service
