---
- name: Copy Prometheus service configuration
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  notify: 
    - Enable Prometheus service
    - Restart Prometheus service
