# ---
# - name: Install Loki Docker Plugin
#   ansible.builtin.command:
#     cmd: docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
#   register: plugin_install

# - name: Restart Docker
#   ansible.builtin.service:
#     name: docker
#     state: restarted
#   when: plugin_install is changed
