---
- name: Configure Wordpres server with NRPE, node_exporter, and apache_exporter
  import_playbook: wordpress.yml

- name: Configure Docker server with NRPE and docker_exporter
  import_playbook: docker.yml

# - name: Configure Nagios server with NRPE
#   import_playbook: nagios.yml

- name: Configure Prometheus server
  import_playbook: prometheus.yml

- name: Configure Loki server
  import_playbook: loki.yml

- name: Configure Grafana server
  import_playbook: grafana.yml
