---
- name: Install and Launch Wordpress 
  hosts: wordpress
  user: ec2-user
  become: yes
  vars_files:
    - mysql
    - wordpress
    - nagios
    - prometheus

  roles:
    - mysql
    - wordpress
    - nrpe
    - node_exporter
    - apache_exporter
